sudo: false
language: node_js
services: mongodb
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
cache:
  directories:
    - node_modules
script:
  - npm run test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
