sudo: false
language: node_js
services: mongodb
node_js:
- 7
- 8
- 9
- 10
cache:
  directories:
  - node_modules
script:
- npm run test
after_script:
- npm install codecov
- "./node_modules/.bin/codecov"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: caique/koa-mongo-driver
