version: '3.6'
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    networks:
      - koa-mongo-driver

networks:
  koa-mongo-driver:
